name: Build project

on: 
  push:
    branches:
      - develop 
  pull_request:
    branches:
      - develop

jobs:
  buildForAllPlatforms:
    name: Build for ${{ matrix.targetPlatform }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        targetPlatform:
          - StandaloneOSX # Build a macOS standalone (Intel 64-bit).
          - StandaloneWindows # Build a Windows standalone.
          - StandaloneWindows64 # Build a Windows 64-bit standalone.
          - StandaloneLinux64 # Build a Linux 64-bit standalone.
          - WebGL # WebGL.
    steps:
      - uses: actions/checkout@v2
        name: Checkout Source
        with:
          fetch-depth: 0
          lfs: true

      - uses: actions/cache@v2
        name: Check Cache
        with:
          path: Library
          key: Library-${{ matrix.targetPlatform }}
          restore-keys: Library-

      - uses: game-ci/unity-builder@v2
        name: Build for Platform - ${{ matrix.targetPlatform }}
        env:
          UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}
        with:
          targetPlatform: ${{ matrix.targetPlatform }}

      - uses: actions/upload-artifact@v2
        name: Archive Artifacts
        with:
          name: Build-${{ matrix.targetPlatform }}-develop
          path: build/${{ matrix.targetPlatform }}
      
      - uses: montudor/actions-zip@v1
        name: "Zip Builds - ${{ matrix.targetPlatform }}"
        if: github.event.action == 'published'
        with:
          args: zip -qq -r build/build-${{ matrix.targetPlatform }}.zip build/${{ matrix.platform }}
      
